### ISSUE TITLE
Training error with different encoder

### ISSUE THREAD

**Issue by IceIce1ce** [fyw1999/MovingDroneCrowd#9]
Hi author, thanks for your great code. I found that the VGG16_FPN encoder can train well. However, when I switch to ResNet50_FPN, the code has the problem:

Traceback (most recent call last):
  File "/home/vsw/Desktop/MovingDroneCrowd/train.py", line 238, in <module>
    cc_trainer.forward()
  File "/home/vsw/Desktop/MovingDroneCrowd/train.py", line 82, in forward
    self.train()
  File "/home/vsw/Desktop/MovingDroneCrowd/train.py", line 101, in train
    pre_global_den, gt_global_den, pre_share_den, gt_share_den, pre_in_out_den, gt_in_out_den, loss_dict = self.model(img, target) # [2, 1, 768, 1024]
                                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsw/miniconda3/envs/drone/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsw/miniconda3/envs/drone/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vsw/Desktop/MovingDroneCrowd/model/VIC.py", line 82, in forward
    gt_share_dot_map[pair_idx * 2 + 1, 0, share_coords1[:, 1], share_coords1[:, 0]] = 1
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Moreover, the drive link of the counter checkpoint is invalid. Can you check your code and your download link again?

**Comment by fyw1999** [comment]
Thank you for your attention. I have fixed the bug when using restnet50 as the backbone. However, in the paper, I did not fully test the effect of using resnet50, so there might still be potential issues. Also, I did not provide additional pre-trained counter of resnet50. Additionally, I added the download link for Baidu Netdisk yesterday. After my testing, all the download links are currently valid. If there are any further issues, please contact me again.

**Comment by IceIce1ce** [comment]
Hi author, I had tested the training and testing code with both VGG16_FPN and Twins encoders, they are work well. Therefore, I think the code only has the problem with the Resnet50 encoder. If the code have any further issues, I will open a new issue later. Thanks for your help.
